### ISSUE TITLE
1.0.0 Update to NETCore RC2 + some refactoring.

### ISSUE THREAD

**Issue by kroniak** [tmenier/Flurl#82]
I am planning big work to Flurl.Http 1.0.0
This issue is for discuss. PR will be added to here.

Goals:

- [x] Update all xproj to RC2 (cli), no more DNX.
- [x] Create one projects to Flurl\Flurl.Http with targeting NET Platform 1.4 (1.1) + net45 + Profile111.
- [x] Add win10 uap supporting #43
- [x] Fix Xamarin problem #79
- [x] Full cross platfrorm (non windows) build.
- [x] Setup AppVeyor build #83 
- [x] Bug in parallel testing download file #85
- [x] Bug in net core environment #86
- [x] Misc code refactoring

All changes will be added to dev branch.

**Comment by tmenier** [comment]
Sounds great. I'm really glad you are tackling these platform targeting issues, that's definitely where I need to the most help. I'd planned to look at #67 at some point but if you want to take it go ahead. It could be tricky. Since we're usually dealing with async code, I think you'll want to look at Logical CallContext for this.

http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html

Even then, the code a user is testing could be multithreaded in which case this could break down. I'll be interested to see what you come up with though.

**Comment by kroniak** [comment]
Combine all targets to one projects is very very hard. I make 2 branches with 2 different strategies. I hate PCL targets)))

**Comment by kroniak** [comment]
Added some new goals. Look init message.

**Comment by kroniak** [comment]
All things was implement except HttpTest.

**Comment by tmenier** [comment]
I'll just move this to "ready" since HttpTest is covered by #67

**Comment by tmenier** [comment]
FYI - just published, good read: https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/

**Comment by kroniak** [comment]
@tmenier Our PCL references doesn't support netstandard.

I think that we need to move HttpTest work 67 to 1.1 version.

Can you change versions on dev to Flurl 2.1-pre\ Flurl.Http 1.1-pre and upload to nuget feed? I see time to do it.

I am reopening PR to master.

**Comment by tmenier** [comment]
I noticed we're still building against .NET Core RC2. The full RTM is available and is supported by AppVeyor. Think we should upgrade?

https://www.appveyor.com/updates/2016/06/27

It sort of makes sense for Flurl.Http 1.0 to coincide with .NET Core 1.0 RTM (or at least I think it's sort of cool).

**Comment by tmenier** [comment]
Actually, maybe it doesn't matter. I installed the latest 1.0 SDK (I never had RC2) and it all built, tests passed, and no source changed. So cancel that.

**Comment by kroniak** [comment]
@tmenier I see that using net core 1.0.0 

Using dotnet 'C:\Users\appveyor\AppData\Local\Microsoft\dotnet\dotnet.exe'
1.0.0-preview3-003171

1.0.0-preview2 is core 1.0.0 CLI util.

https://ci.appveyor.com/project/kroniak/flurl/build/1.0.0-dev-31
